apiVersion: v2
version: 4.11.11
appVersion: v4.11.11
kubeVersion: '^1.14.0-0'
name: metacontroller-helm
description: Writing kubernetes controllers can be simple
home: https://metacontroller.github.io/metacontroller/
sources:
  - https://github.com/metacontroller/metacontroller
engine: gotpl
type: application
