apiVersion: v2
version: v4.5.2
appVersion: v4.5.2
kubeVersion: '^1.14.0-0'
name: metacontroller-helm
description: Writing kubernetes controllers can be simple
home: https://metacontroller.github.io/metacontroller/
sources:
  - https://github.com/metacontroller/metacontroller
engine: gotpl
type: application
