apiVersion: v2
version: v2.2.3
appVersion: v2.2.3
kubeVersion: '^1.8.0-0'
name: metacontroller
description: Writing kubernetes controllers can be simple
home: https://metacontroller.github.io/metacontroller/
sources:
  - https://github.com/metacontroller/metacontroller
engine: gotpl
type: application
