apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "metacontroller.fullname" . }}
  namespace: {{ include "metacontroller.namespace" . }}
  labels:
    {{- include "metacontroller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  serviceName: ''
  selector:
    matchLabels:
      {{- include "metacontroller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metacontroller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "metacontroller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /usr/bin/metacontroller
          args:
          - --zap-log-level={{ .Values.zap.logLevel | default 4 }}
          - --discovery-interval={{ .Values.discoveryInterval | default "20s" }}
          {{ if .Values.zap.devel -}}
          - --zap-devel={{.Values.zap.devel}}
          {{ end }}
          {{- if .Values.zap.encoder -}}
          - --zap-encoder={{.Values.zap.encoder}}
          {{ end }}
          {{- if .Values.zap.stacktraceLevel -}}
          - --zap-stacktrace-level={{.Values.zap.stacktraceLevel}}
          {{ end }}
          {{- if .Values.cacheFlushInterval -}}
          - --cache-flush-interval={{.Values.cacheFlushInterval}}
          {{ end -}}
          {{- range $value := .Values.commandArgs }}
          - {{ $value | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
