name: Documentation

on:
  push:
    branches:
      - master

jobs:
  gh-pages:
    runs-on: ubuntu-20.04
    container:
      image: "michaelfbryan/mdbook-docker-image:latest"
    if: github.repository_owner == 'metacontroller'
    steps:
    - uses: actions/checkout@v3
    - name: Build mdbook
      run: |
        cd docs
        mdbook build
    - name: Install git
      run: |
        apt-get update
        apt-get install -y git
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./docs/book/html
        publish_branch: gh-pages
  dockerhub-readme:
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'metacontroller'
    steps:
    - uses: actions/checkout@v3
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: metacontrollerio/metacontroller
        short-description: "Lightweight Kubernetes controllers as a service"
        readme-filepath: ./DOCKERHUB-README.md

