---
name: Release docker image
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release-docker:
    name: Release docker image
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'metacontroller'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: '[alpine] Docker metainformations'
      id: docker_meta_alpine
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: metacontrollerio/metacontroller # list of Docker images to use as base name for tags
    - name: '[alpine] Build and push'
      id: docker_build_alpine
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta_alpine.outputs.tags }}
        labels: ${{ steps.docker_meta_alpine.outputs.labels }}
    - name: '[distroless] Docker metainformations'
      id: docker_meta_distroless
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: metacontrollerio/metacontroller # list of Docker images to use as base name for tags
        sep-tags: '-distroless\n'
    - name: '[distroless] Build and push'
      id: docker_build_distroless
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.distroless
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta_distroless.outputs.tags }}-distroless
        labels: ${{ steps.docker_meta_distroless.outputs.labels }}
    - name: '[distroless-debug] Docker metainformations'
      id: docker_meta_distroless_debug
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: metacontrollerio/metacontroller # list of Docker images to use as base name for tags
        sep-tags: '-distroless-debug\n':  
    - name: '[distroless-debug] Build and push'
      id: docker_build_distroless_debug
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.distroless-debug
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta_distroless_debug.outputs.tags }}-distroless-debug
        labels: ${{ steps.docker_meta_distroless_debug.outputs.labels }}
